target  = ../main
object  = \
  variablesMod.o \
  utilitiesMod.o \
  shapeFuncMod.o \
  ioUtilityMod.o \
  initiatorMod.o \
  rkgSolverMod.o \
  pBoundaryMod.o \
  fBoundaryMod.o \
  main.o

FC = gfortran

FFLAGS  = -O3
LDFLAGS =


.SUFFIXES: .o .f90

%.o: %.f90
	$(FC) -c $< $(FFLAGS) $(LDFLAGS)

%.mod: %.f90 %.o
	@:

$(target): $(object)
	$(FC) -o $@ $(object) $(FFLAGS) $(LDFLAGS)


.PHONY:clean all

clean:
	$(RM) $(target) $(object) *.mod

all: clean $(target)
